### ISSUE TITLE
MC-HEVC Support

### ISSUE THREAD

**Issue by elliotttate** [finnvoor/fx-upscale#15]
It doesn't appear that the command-line version has MC-HEVC support like Unsqueeze does. Any chance this could be added? 🙏

**Comment by finnvoor** [comment]
Hi, spatial videos should definitely be supported. I just tried one and it worked, are you seeing a specific issue?

**Comment by elliotttate** [comment]
Thanks! I was doing something wrong on my end. Appreciate all you do!! Btw, your upscaler has been added to: https://github.com/cbusillo/BD_to_AVP
